([
    'Level',
    'Rank',
    'Age',
    'Life',
    'Life Max',
    'Friends',
    'Enemies',
    'Forum posts',
    'Forum score',
    'Attacks won',
    'Attacks lost',
    'Attacks stalemated',
    'Defends won',
    'Defends lost',
    'Defends stalemated',
    'Win/Loss ratio',
    'Times ran away',
    'Foes ran away',
    'Best kill streak',
    'Critical hits',
    'Rounds fired',
    'Stealth attacks',
    'Money mugged',
    'Largest mug',
    'Highest level beaten',
    'Total respect gained',
    'Items bought from market',
    'Auctions won',
    'Points bought',
    'Items auctioned',
    'Points sold',
    'Items bought from Big Al\'s',
    'Items sent',
    'Trades made',
    'Bazaar customers',
    'Bazaar sales',
    'Bazaar income',
    'Times jailed',
    'Time spent in jail',
    'People busted',
    'Failed busts',
    'People bailed',
    'Bail fees',
    'Times in hospital',
    'Time spent in hospital',
    'Medical items used',
    'People revived',
    'Revives received',
    'Medical items stolen',
    'Heavy artillery',
    'Machine guns',
    'Rifles',
    'Sub machine guns',
    'Shotguns',
    'Pistols',
    'Temporary weapons',
    'Piercing weapons',
    'Slashing weapons',
    'Clubbed weapons',
    'Machinery',
    'Mails sent',
    'Mails sent to friends',
    'Mails sent to faction',
    'Mails sent to colleagues',
    'Mails sent to spouse',
    'Classified ads placed',
    'Personals placed',
    'Criminal offences',
    'Selling illegal goods',
    'Theft',
    'Auto theft',
    'Drug deals',
    'Computer crimes',
    'Fraud',
    'Murder',
    'Other',
    'Bounties placed',
    'Spent on bounties',
    'Bounties collected',
    'Money rewarded',
    'Bounties received',
    'Items found',
    'Items trashed',
    'Dump searches',
    'Items found in dump',
    'Times travelled',
    'Items bought abroad',
    'Hunting skill',
    'Argentina',
    'Mexico',
    'Dubai',
    'Hawaii',
    'Japan',
    'United Kingdom',
    'South Africa',
    'Switzerland',
    'China',
    'Canada',
    'Cayman Islands',
    'Drugs used',
    'Times overdosed',
    'Cannabis taken',
    'Ecstasy taken',
    'Ketamine taken',
    'LSD taken',
    'Opium taken',
    'Shrooms taken',
    'Speed taken',
    'PCP taken',
    'Xanax taken',
    'Vicodin taken',
    'Logins',
    'Time played',
    'Merits bought',
    'Energy refills',
    'Times trained by director',
    'Army spying',
    'Stat enhancers used',
    'Viruses coded',
    'Days been a donator',
    'Times voted',
    'Critical hits %',
    'Stealth attacks %',
    'Times overdosed %'
])