var ranksDatalist = {
    1:'Absolute beginner',
    2:'Beginner',
    3:'Inexperienced',
    4:'Rookie',
    5:'Novice',
    6:'Below Average',
    7:'Average',
    8:'Reasonable',
    9:'Above Average',
    10:'Competent',
    11:'Highly competent',
    12:'Veteran',
    13:'Distinguished',
    14:'Highly distinguished',
    15:'Professional',
    16:'Star',
    17:'Master',
    18:'Outstanding',
    19:'Celebrity',
    20:'Supreme',
    21:'Idolised',
    22:'Champion',
    23:'Heroic',
    24:'Legendary',
    25:'Elite',
    26:'Invincible'
}