var titlesDatalist = [
    'Antagonist',
    'Bondsman',
    'Booster',
    'Buster',
    'Coward',
    'Citizen',
    'Damage Dealer',
    'Deserter',
    'Druggy',
    'Egotist',
    'Felon',
    'Healer',
    'Hitman',
    'Horder',
    'Importer',
    'Intimidator',
    'Investor',
    'Jobsworth',
    'Killer',
    'Loser',
    'Marksman',
    'Merchant',
    'Newcomer',
    'One Hit Killer',
    'Outcast',
    'Punchbag',
    'Samaritan',
    'Sage',
    'Scavenger',
    'Silent Killer',
    'Soldier',
    'Socialite',
    'Tank',
    'Thief',
    'Tourist',
    'Trader',
    'Tycoon'
]